export default {
  success: true,
  data: {
    memes: [
      {
        ID: 1,
        bottomText: "Good!",
        image: "http://imgflip.com/s/meme/Grumpy-Cat.jpg",
        name: "Grumpy Cat",
        rank: 10,
        tags: "Tardar Sauce, Tabatha Bundesen, Felis domesticus",
        topText: "",
      },
      {
        ID: 7,
        bottomText: "Winter is Coming",
        image: "https://imgflip.com/s/meme/Brace-Yourselves-X-is-Coming.jpg",
        name: "Brace Yourselves",
        rank: 20,
        tags: "Winter is Coming, Ned Stark, Sean Bean, Game of Thrones, GOT, Imminent Ned",
        topText: "Brace Yourselves",
      },
      {
        ID: 3,
        bottomText: "Or just ___",
        image: "https://imgflip.com/s/meme/Futurama-Fry.jpg",
        name: "Futurama Fry",
        rank: 30,
        tags: "Not Sure If",
        topText: "Not sure if ___",
      },
      {
        ID: 5,
        bottomText: "Walk into mordor",
        image: "https://imgflip.com/s/meme/One-Does-Not-Simply.jpg",
        name: "One Does Not Simply",
        rank: 40,
        tags: "One Does Not Simply Walk Into Mordor, Boromir, Sean Bean, Ned Stark, LOTR, Lord of the rings, One Ring",
        topText: "One does not simply",
      },
      {
        ID: 4,
        bottomText: null,
        image: "https://imgflip.com/s/meme/Bad-Luck-Brian.jpg",
        name: "Bad Luck Brian",
        rank: 50,
        tags: "Bad Luck Kyle",
        topText: null,
      },
      {
        ID: 6,
        bottomText: null,
        image: "https://imgflip.com/s/meme/First-World-Problems.jpg",
        name: "First World Problems",
        rank: 60,
        tags: "Crying, FWP, White Whine",
        topText: null,
      },
      {
        ID: 2,
        bottomText: "Who ___",
        image: "https://imgflip.com/s/meme/Am-I-The-Only-One-Around-Here.jpg",
        name: "Am I The Only One Around Here",
        rank: 70,
        tags: "Dude Abides, Big Lebowski, Angry Walter Sobchak",
        topText: "Am I the only one around here",
      },
      {
        ID: 8,
        bottomText: "Success!",
        image: "https://imgflip.com/s/meme/Success-Kid.jpg",
        name: "Success Kid",
        rank: 80,
        tags: "I hate sandcastles, eating sand",
        topText: null,
      },
      {
        ID: 9,
        bottomText: null,
        image: "https://imgflip.com/s/meme/Awkward-Moment-Sealion.jpg",
        name: "Awkward Moment Seal",
        rank: 90,
        tags: "Poker Face",
        topText: null,
      },
      {
        ID: 10,
        bottomText: null,
        image: "https://imgflip.com/s/meme/Confession-Bear.jpg",
        name: "Confession Bear",
        rank: 100,
        tags: "Animal, Advice",
        topText: null,
      },
      {
        ID: 15,
        bottomText: "Enough!",
        image: "https://imgflip.com/s/meme/Batman-Slapping-Robin.jpg",
        name: "Batman Slapping Robin",
        rank: 110,
        tags: "My parents are dead",
        topText: "",
      },
      {
        ID: 16,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg",
        name: "Grandma Finds the Internet",
        rank: 120,
        tags: "Internet Grandma Surprise",
        topText: "",
      },
      {
        ID: 11,
        bottomText: '"Aliens"',
        image: "https://imgflip.com/s/meme/Ancient-Aliens.jpg",
        name: "Ancient Aliens",
        rank: 130,
        tags: "History Channel Guy, Giorgio A Tsoukalos",
        topText: "",
      },
      {
        ID: 14,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Creepy-Condescending-Wonka.jpg",
        name: "Condescending Wonka",
        rank: 140,
        tags: "Creepy WIlly Wonka, Willy wonka and the chocolate factory, Gene Wilder",
        topText: "",
      },
      {
        ID: 12,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Actual-Advice-Mallard.jpg",
        name: "Actual Advice Mallard",
        rank: 150,
        tags: "Green, Duck, Advice",
        topText: "",
      },
      {
        ID: 13,
        bottomText: "But when I do ___",
        image:
          "https://imgflip.com/s/meme/The-Most-Interesting-Man-In-The-World.jpg",
        name: "The Most Interesting Man in the World",
        rank: 160,
        tags: "Jonathan Goldsmith",
        topText: "I don't always ___",
      },
      {
        ID: 56,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Philosoraptor.jpg",
        name: "Philosoraptor",
        rank: 165,
        tags: "What if, dinosaur, Velociraptor, metaphysical inquiries",
        topText: "What if ...",
      },
      {
        ID: 17,
        bottomText: "Everywhere",
        image: "https://imgflip.com/s/meme/X-Everywhere.jpg",
        name: "X, X Everywhere",
        rank: 170,
        tags: "Toy story, Buzz lightyear, Woody",
        topText: "___, ___",
      },
      {
        ID: 20,
        bottomText: "That'd be great",
        image: "https://imgflip.com/s/meme/That-Would-Be-Great.jpg",
        name: "That would be great",
        rank: 180,
        tags: "Bill Lumbergh, Office Space",
        topText: "Yeah, If you could just ___",
      },
      {
        ID: 18,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Good-Guy-Greg.jpg",
        name: "Good Guy Greg",
        rank: 180,
        tags: "ggg",
        topText: "      ",
      },
      {
        ID: 258,
        bottomText: "Show Me What You Got",
        image: "https://i.imgur.com/6Ln3hp8.png",
        name: "Show Me What You Got",
        rank: 188,
        tags: "Rick and Morty, Giant Heads, Dan, Justin, Adult Swim",
        topText: "",
      },
      {
        ID: 55,
        bottomText: "Ain't nobody got time for that",
        image: "https://imgflip.com/s/meme/Aint-Nobody-Got-Time-For-That.jpg",
        name: "Ain't nobody got time for that",
        rank: 205,
        tags: "sweet brown Kimberly Wilkins",
        topText: "",
      },
      {
        ID: 54,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Insanity-Wolf.jpg",
        name: "Insanity Wolf",
        rank: 205,
        tags: "animal, insane, dog",
        topText: "",
      },
      {
        ID: 22,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Conspiracy-Keanu.jpg",
        name: "Conspiracy Keanu",
        rank: 210,
        tags: "Keanu Reeves, Bill and Ted, Excellent Adventure, Neo",
        topText: "What If",
      },
      {
        ID: 61,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Sudden-Clarity-Clarence.jpg",
        name: "Sudden Clarity Clarence",
        rank: 211,
        tags: "realization, what if, holy shit",
        topText: "",
      },
      {
        ID: 23,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Unpopular-Opinion-Puffin.jpg",
        name: "Unpopular Opinion Puffin",
        rank: 220,
        tags: "advice, animal",
        topText: "",
      },
      {
        ID: 24,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Scumbag-Steve.jpg",
        name: "Scumbag Steve",
        rank: 230,
        tags: "cap, bad guy, gangsta",
        topText: "",
      },
      {
        ID: 25,
        bottomText: "And everyone loses their minds",
        image: "https://imgflip.com/s/meme/And-everybody-loses-their-minds.jpg",
        name: "Everyone Loses Their Minds",
        rank: 240,
        tags: "Joker, The Dark Knight, Batman, Heath Ledger",
        topText: "",
      },
      {
        ID: 26,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Picard-Wtf.jpg",
        name: "Why the F",
        rank: 250,
        tags: "Star Trek the Next Generation, TNG, Patrick Stewert, Captain, Annoyed, Jean Luc Picard, Enterprise, Why the Fuck",
        topText: "Why the F",
      },
      {
        ID: 27,
        bottomText: "",
        image: "https://imgflip.com/s/meme/10-Guy.jpg",
        name: "Stoner Stanley",
        rank: 250,
        tags: "10 guy, high, weed, marijuana, stoned",
        topText: "",
      },
      {
        ID: 29,
        bottomText: "Aaaaand It's Gone",
        image: "http://i.ytimg.com/vi/DNLob2E_Q5s/maxresdefault.jpg",
        name: "Aaaaand It's Gone",
        rank: 260,
        tags: "And, South Park, Margaritaville",
        topText: "",
      },
      {
        ID: 30,
        bottomText: "False.",
        image: "http://www.mememaker.net/static/images/templates/747303.jpg",
        name: "Schrute Facts",
        rank: 270,
        tags: "The office, Dwight Schrute, False,",
        topText: "",
      },
      {
        ID: 28,
        bottomText: "And at this point I'm too afraid to ask",
        image: "https://imgflip.com/s/meme/Afraid-To-Ask-Andy.jpg",
        name: "Afraid to Ask Andy",
        rank: 270,
        tags: "Andy Dwyer, Chris Pratt, at this point I'm too afraid to ask",
        topText: "I don't know what ___ is",
      },
      {
        ID: 57,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Unhelpful-High-School-Teacher.jpg",
        name: "Unhelpful High School Teacher",
        rank: 277,
        tags: "school",
        topText: "",
      },
      {
        ID: 58,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Engineering-Professor.jpg",
        name: "Engineering Professor",
        rank: 278,
        tags: "college, no help",
        topText: "",
      },
      {
        ID: 32,
        bottomText: "",
        image: "http://images.memes.com/character/meme/facepalm.jpg",
        name: "Facepalm (Picard)",
        rank: 290,
        tags: "Jean Luc Picard, Star Trek TNG, Enterprise, Deja !",
        topText: "",
      },
      {
        ID: 34,
        bottomText: "",
        image: "https://imgflip.com/s/meme/confession-kid.jpg",
        name: "Confession Kid",
        rank: 320,
        tags: "facepalm kid, when i was a kid, mistake, silly, stupid",
        topText: "",
      },
      {
        ID: 113,
        bottomText: "It's Over 9000!",
        image: "https://i.ytimg.com/vi/DZ7D2g9SUkU/maxresdefault.jpg",
        name: "It's Over 9000",
        rank: 363,
        tags: "Vegeta, Dragon Ball Z, Saiyan Saga, Power Level",
        topText: "",
      },
      {
        ID: 38,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Third-World-Skeptical-Kid.jpg",
        name: "So you're telling me",
        rank: 370,
        tags: "Third World Skeptical Kid",
        topText: "So you're telling me",
      },
      {
        ID: 40,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Third-World-Success-Kid.jpg",
        name: "Third World Success Kid",
        rank: 390,
        tags: "dancing tribal child, problems, africa, black kid, overcoming hardships",
        topText: "",
      },
      {
        ID: 39,
        bottomText: "Too Damn High",
        image:
          "http://i0.kym-cdn.com/photos/images/original/000/374/510/b71.jpg",
        name: "Too Damn High",
        rank: 390,
        tags: "The Rent is, Jimmy McMillan political slogan",
        topText: "",
      },
      {
        ID: 41,
        bottomText: "",
        image: "https://imgflip.com/s/meme/Evil-Toddler.jpg",
        name: "Evil Toddler",
        rank: 400,
        tags: "laughing child, white kid, prank, mischief, smutty",
        topText: "",
      },
    ],
  },
};
